### PR TITLE
Fix/polish

### LINKED ISSUE #13: CSS

### PR DESCRIPTION
**Pull request by BigBike96**
# Description

Clean up files. Remove unused variables

Fixes # (issue)

Fix card stacking bug

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

npm test
run servers and view on screen 
linter

### CODE REVIEW

File: test/RecipeRepository-test.js [hunk 1]
```diff
@@ -104,120 +103,11 @@ describe('Recipe RecipeRepository', () => {
         "dinner"
       ]
     }
-
```
Comment (hoomberto) [inline test/RecipeRepository-test.js:107]: How did we miss this until now?

File: src/styles.css [hunk 2]
```diff
@@ -368,41 +302,20 @@ form input {
...
+/* MEDIA QUERIES */
 @media screen and (max-width: 1200px) {
-/*
-  nav {
-    width: 170%;
-  } */
-
   .tag-options {
-    font-size: 0.75em
+    font-size: 0.75em;
```
Comment (hoomberto) [inline src/styles.css:318]: Like the use of dynamic font here

**Review by hoomberto — APPROVED** [review]
